src/mi13/VitrineBundle/Entity/Client.php
<?php

namespace mi13\VitrineBundle\Entity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * Client
 */
class Client implements UserInterface
{
    /**
     * @var int
     */
    private $id;

    /**
     * @var string
     */
    private $name;

    /**
     * @var string
     */
    private $email;

    /**
     * @var string
     */
    private $password;


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Client
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }
    
    public function getUsername() {
        return $this->getEmail();
    }
    
    public function getSalt() {
        return null;
    }
    
    public function isAdministrateur() {
        return ($this->getEmail() == 'admin@admin.fr');
    }
    
    public function getRoles() {
        if ($this->isAdministrateur()) {
            return array('ROLE_ADMIN');
        } else {
            return array('ROLE_USER');
        }
    }
    
    public function eraseCredentials() { }
    
    public function serialize() {
        return serialize(array($this-id, $this->name, $this-email, $this->password));
    }
    
    public function unserialize($serialized) {
        list($this->id, $this->name, $this->email, $this->password) = unserialize($serialized);
    }

    /**
     * Set email
     *
     * @param string $email
     *
     * @return Client
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set password
     *
     * @param string $password
     *
     * @return Client
     */
    public function setPassword($password)
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Get password
     *
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }
    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $commandes;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->commandes = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add commande
     *
     * @param \mi13\VitrineBundle\Entity\Commande $commande
     *
     * @return Client
     */
    public function addCommande(\mi13\VitrineBundle\Entity\Commande $commande)
    {
        $this->commandes[] = $commande;

        return $this;
    }

    /**
     * Remove commande
     *
     * @param \mi13\VitrineBundle\Entity\Commande $commande
     */
    public function removeCommande(\mi13\VitrineBundle\Entity\Commande $commande)
    {
        $this->commandes->removeElement($commande);
    }

    /**
     * Get commandes
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getCommandes()
    {
        return $this->commandes;
    }
    
    public function __toString() {
        return $this->getEmail();
    }
}

src/mi13/VitrineBundle/Controller/DefaultController.php
<?php

namespace mi13\VitrineBundle\Controller;

use mi13\VitrineBundle\Entity\Client;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class DefaultController extends Controller
{
    public function indexAction($name) {
        $bestSellers = $this->get('produits_plus_vendus')->getPopularProducts(3);
        $articles = [];
        foreach ($bestSellers as $articleId => $quantitySold) {
            $articles[$quantitySold] = 
                    $this->getDoctrine()->getManager()
                    ->getRepository('mi13VitrineBundle:Article')
                    ->find($articleId);
        }
        return $this->render('mi13VitrineBundle:Default:index.html.twig',
                array('name' => $name, 'articles' => $articles));
    }
    
    public function signUpAction(Request $request) {
        $client = new Client();
        $form = $this->createForm('mi13\VitrineBundle\Form\ClientType', $client);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $encoder = $this->container->get('security.password_encoder');
            $encoded = $encoder->encodePassword($client, $client->getPassword());
            $client->setPassword($encoded);
            $em->persist($client);
            $em->flush();

            return $this->redirectToRoute('mi13_vitrine_accueil', array('name' => $client->getName()));
        }

        return $this->render('mi13VitrineBundle:Default:signup.html.twig', array(
            'client' => $client,
            'form' => $form->createView(),
        ));
    }
    
    public function mentionsAction() {
        return $this->render('mi13VitrineBundle:Default:mentions.html.twig');
    }
    
    public function catalogueAction() {
        $categories = $this->getDoctrine()->getManager()->getRepository('mi13VitrineBundle:Categorie')
                ->findAll();
        return $this->render('mi13VitrineBundle:Default:catalogue.html.twig',
                array('categories' => $categories));
    }
    
    public function articlesParCategorieAction($id_categorie) {
        $manager = $this->getDoctrine()->getManager();
        $categorie = $manager->getRepository('mi13VitrineBundle:Categorie')->findOneBy(array('id' => $id_categorie));
        $articles = $manager->getRepository('mi13VitrineBundle:Article')
                ->findBy(array('categorie' => $id_categorie));
        return $this->render('mi13VitrineBundle:Default:articlesParCategorie.html.twig',
                array('categorie' => $categorie, 'articles' => $articles));
    }
    
    public function backofficeAction() {
        return $this->render('mi13VitrineBundle:Default:backoffice.html.twig');
    }
        
}

src/mi13/VitrineBundle/Resources/views/Default/articlesParCategorie.html.twig
{% extends "mi13VitrineBundle:Default:layout.html.twig" %}

{% block content %}

<h1>Articles</h1>
<h3>Catégorie {{ categorie.name | lower }}</h3>

{#
<ul class="collection" id="article">
    {% for article in articles %}
        <li class="collection-item">
            {{ article.label }} - {{ article.price }}
            - <a href="{{ path('mi13_vitrine_ajoutArticle', {'id_article': article.id, 'quantite': 1}) }}">Ajouter au panier</a>
        </li>
    {% endfor %}
</ul>
#}

{% if articles|length > 0 %}
    <table>
        <thead>
            <tr>
                <th>Nom</th>
                <th>Stock</th>
                <th>Prix</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for article in articles %}
            <tr>
                <td>{{ article.label }}</td>
                <td>{{ article.stock }}</td>
                <td>{{ article.price }}</td>
                <td>
                    {% if article.stock > 0 %}
                        <a href="{{ path('mi13_vitrine_ajoutArticle', {'id_article': article.id, 'quantite': 1}) }}">Ajouter au panier</a>
                    {% else %}
                        <span>Rupture de stock</span>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% else %}
    <div>Aucun article trouvé.</div>
{% endif %}

{% endblock %}

src/mi13/VitrineBundle/Resources/views/Default/backoffice.html.twig
{% extends "mi13VitrineBundle:Default:layout.html.twig" %}

{% block content %}
    <h1>{% trans %}mi13.vitrine.backoffice.title{% endtrans %}</h1>

    <div id="backoffices" class="collection">
        <a href="{{ path('article_index') }}" class="collection-item">
            {% trans %}mi13.vitrine.backoffice.articles{% endtrans %}
        </a>
        <a href="{{ path('categorie_index') }}" class="collection-item">
            {% trans %}mi13.vitrine.backoffice.categories{% endtrans %}
        </a>
        <a href="{{ path('client_index') }}" class="collection-item">
            {% trans %}mi13.vitrine.backoffice.clients{% endtrans %}
        </a>
        <a href="{{ path('commande_index') }}" class="collection-item">
            {% trans %}mi13.vitrine.backoffice.commandes{% endtrans %}
        </a>
    </div>

{% endblock %}

src/mi13/VitrineBundle/Resources/views/Default/catalogue.html.twig
{% extends "mi13VitrineBundle:Default:layout.html.twig" %}

{% block content %}

    <h1>{% trans %}mi13.vitrine.catalog{% endtrans %}</h1>
    <div id="categories" class="collection">
        {% for categorie in categories %}
            <a href="{{ path('mi13_vitrine_articlesParCategorie', {'id_categorie': categorie.id}) }}" class="collection-item">{{ categorie.name }}</a>
        {% endfor %}
    </div>

{% endblock %}

src/mi13/VitrineBundle/Resources/views/Default/footer.html.twig
<footer class="page-footer orange">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <h5 class="white-text">La Vitrine</h5>
                <p class="grey-text text-lighten-4">
                    {% trans %}mi13.vitrine.footer.description{% endtrans %}
                </p>
            </div>
            <div class="col l3 s12">
                <h5 class="white-text">Informations</h5>
                <ul>
                    <li><a class="brown-text" href="#!">Lien 1</a></li>
                    <li><a class="brown-text" href="#!">Lien 2</a></li>
                    <li><a class="brown-text" href="#!">Lien 3</a></li>
                    <li><a class="brown-text" href="#!">Lien 4</a></li>
                </ul>
            </div>
            <div class="col l3 s12">
                <h5 class="white-text">Support</h5>
                <ul>
                    <li><a class="brown-text" href="#!">{% trans %}mi13.vitrine.footer.contactUs{% endtrans %}</a></li>
                    <li><a class="brown-text" href="#!">{% trans %}mi13.vitrine.footer.guarantee{% endtrans %}</a></li>
                    <li><a class="brown-text" href="#!">{% trans %}mi13.vitrine.footer.opinion{% endtrans %}</a></li>
                    <li><a class="brown-text" href="#!">{% trans %}mi13.vitrine.footer.sav{% endtrans %}</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            {#Made with <a class="orange-text text-lighten-3" href="http://materializecss.com">Materialize</a>#}
        </div>
    </div>
</footer>
      

src/mi13/VitrineBundle/Resources/views/Default/index.html.twig
{% extends "mi13VitrineBundle:Default:layout.html.twig" %}

{% block content %}

    <h1>{{ 'mi13.vitrine.index.welcome'|trans({'%name%': name}) }}</h1>
    
    <h3>{% trans %}mi13.vitrine.index.bestsellers{% endtrans %}</h3>
    
    {% if articles|length > 0 %}
    <table>
        <thead>
            <tr>
                <th>Nom</th>
                <th>Prix</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for article in articles %}
            <tr>
                <td>{{ article.label }}</td>
                <td>{{ article.price }}</td>
                <td>
                    {% if article.stock > 0 %}
                        <a href="{{ path('mi13_vitrine_ajoutArticle', {'id_article': article.id, 'quantite': 1}) }}">Ajouter au panier</a>
                    {% else %}
                        <span>Rupture de stock</span>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% else %}
    <div>Aucun article trouvé.</div>
{% endif %}

{% endblock %}

src/mi13/VitrineBundle/Resources/views/Default/layout.html.twig
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
        <title>La Vitrine</title>

        <!-- CSS  -->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link href="{{ asset('bundles/mi13vitrine/css/materialize.min.css') }}" rel="stylesheet" type="text/css"/>
        <link href="{{ asset('bundles/mi13vitrine/css/style.css') }}" type="text/css" rel="stylesheet" media="screen,projection"/>
    </head>
    <body>

        {% include "mi13VitrineBundle:Default:navbar.html.twig" %}

        <div class="row">
            {% if app.session.get('panier') != null and app.session.get('panier').getContenu() != null %}
                <div class="col s9">
                {% else %}
                    <div class="col s12">
                    {% endif %}
                    {% block content %}
                        <p>left content</p>
                    {% endblock %}
                </div>
                {% if app.session.get('panier') != null and app.session.get('panier').getContenu() != null %}
                    <div class="col s3">
                        {{ render(controller('mi13VitrineBundle:Panier:panierBlock')) }}
                    </div>
                {% endif %}
            </div>

            {% include "mi13VitrineBundle:Default:footer.html.twig" %}

            <!--JS Scripts-->
            <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
            <script src="{{ asset('bundles/mi13vitrine/js/materialize.min.js') }}"></script>
            <script src="{{ asset('bundles/mi13vitrine/js/init.js') }}"></script>

    </body>
</html>

src/mi13/VitrineBundle/Resources/views/Default/mentions.html.twig
{% extends "mi13VitrineBundle:Default:layout.html.twig" %}

{% block content %}

    <div class="container">
        <h1>{% trans %}mi13.vitrine.mentions.title{% endtrans %}</h1>
        <div>{{ 'mi13.vitrine.mentions.mentions'|trans|nl2br }}</div>
    </div>

{% endblock %}

src/mi13/VitrineBundle/Resources/views/Default/navbar.html.twig
<nav class="light-blue lighten-1" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="/" class="brand-logo">La Vitrine</a>
      <ul class="right hide-on-med-and-down">
        <li><a href="{{ path('mi13_vitrine_accueil') }}">{% trans %}mi13.vitrine.navbar.home{% endtrans %}</a></li>
        <li><a href="{{ path('mi13_vitrine_catalogue') }}">{% trans %}mi13.vitrine.catalog{% endtrans %}</a></li>
        <li><a href="{{ path('mi13_vitrine_mentions') }}">{% trans %}mi13.vitrine.mentions.title{% endtrans %}</a></li>
        {% if app.user %}
        <li><a class="dropdown-trigger" href="#" data-target="userDropdown">
                <span class="material-icons">person</span>
                <span>{{ app.user.username }}</span>
        </a></li>
        {% else %}
        <li><a class="dropdown-trigger" href="#" data-target="guestDropdown">
                {% trans %}mi13.vitrine.navbar.myAccount{% endtrans %}
        </a></li>
        {% endif %}
        <li><a class="dropdown-trigger" href="#" data-target="langDropdown">
                <span class="material-icons">language</span>
        </a></li>
      </ul>

      <ul id="nav-mobile" class="sidenav">
        <li><a href="{{ path('mi13_vitrine_accueil') }}">{% trans %}mi13.vitrine.navbar.home{% endtrans %}</a></li>
        <li><a href="{{ path('mi13_vitrine_catalogue') }}">{% trans %}mi13.vitrine.catalog{% endtrans %}</a></li>
        <li><a href="{{ path('mi13_vitrine_mentions') }}">{% trans %}mi13.vitrine.mentions.title{% endtrans %}</a></li>
      </ul>
      <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    
      {% if app.user %}
      <ul id="userDropdown" class="dropdown-content">
          <li><a href="{{ path('mi13_vitrine_contenuPanier') }}">{% trans %}mi13.vitrine.navbar.myCart{% endtrans %}</a></li>
          {% if is_granted('ROLE_ADMIN') %}
          <li><a href="{{ path('mi13_backoffice') }}">{% trans %}mi13.vitrine.backoffice.title{% endtrans %}</a></li>
          {% endif %}
          <li><a href="{{ path('logout') }}">{% trans %}mi13.vitrine.signOut{% endtrans %}</a></li>
      </ul>
      {% else %}
      <ul id="guestDropdown" class="dropdown-content">
          <li><a href="{{ path('login') }}">{% trans %}mi13.vitrine.signIn{% endtrans %}</a></li>
          <li><a href="{{ path('mi13_vitrine_creer_compte') }}">{% trans %}mi13.vitrine.signUp{% endtrans %}</a></li>
      </ul>
      {% endif %}
      <ul id="langDropdown" class="dropdown-content">
          <li><a href="{{ path('mi13_vitrine_accueil', {'_locale': 'fr'}) }}">
                  <img src="{{ asset('bundles/mi13vitrine/img/fr.png') }}" alt="fr" />
          </a></li>
          <li><a href="{{ path('mi13_vitrine_accueil', {'_locale': 'en'}) }}">
                  <img src="{{ asset('bundles/mi13vitrine/img/us.png') }}" alt="en" />
          </a></li>
    </div>
</nav>
    
<script>
  document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.dropdown-trigger');
    M.Dropdown.init(elems, {hover: true, coverTrigger: false, constrainWidth: false});
  });
</script>

<style>
    a.dropdown-trigger span {
        vertical-align: middle;
    }
    
    #langDropdown li {
        text-align: center;
    }
</style>

src/mi13/VitrineBundle/Resources/views/Default/signup.html.twig
{% extends "mi13VitrineBundle:Default:layout.html.twig" %}

{% block content %}
    <h1>{% trans %}mi13.vitrine.signup.title{% endtrans %}</h1>

    {{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn waves-effect waves-light" type="submit" value="Create">
        {% trans %}mi13.vitrine.validate{% endtrans %} <i class="material-icons right">send</i>
    </button>
    {{ form_end(form) }}

{% endblock %}